spring:
  application:
    name: spring-lab

server:
  port: 8080

app:
  owner: Mautkan Nurbolat
  group: 2405IS
  mail:
    from: no-reply@iitu.kz
    retry-count: 3
    timeout: 5s
    enabled: true
  security:
    token-ttl: 30m
    min-password-length: 8

logging:
  level:
    kz.iitu: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,env,configprops,conditions
  endpoint:
    env:
      show-values: always